version: '3.1'

services:

  db:
    image: icorrea/postgresql:11.7-alpine3.11
    environment:
      POSTGRES_PASSWORD: senha123
      POSTGRES_USER: userncm
      POSTGRES_DB: ncmsdb
    networks:
      - icorrea_net
    volumes:
      - ~/svr/postgresql/api-ncm-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "italiviocorrea@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "senha123"
    ports:
      - 8181:80
    depends_on:
      - db
    networks:
      - icorrea_net

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - icorrea_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - icorrea_net

  mongo:
    image: mongo:4.0
    volumes:
      - $PWD/svr/graylog/mongo_data:/data/db
    networks:
      - icorrea_net

  graylog:
    image: graylog/graylog:3.2
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      #- ./graylog/config:/usr/share/graylog/data/config
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ROOT_PASSWORD_SHA2=1ca7838a7d2add6ce3d020a2ed63c8c29c3419f06771411bb1223651b8743d38
    networks:
      - icorrea_net
    depends_on:
      - elasticsearch
      - mongo

  prometheus:
    image: icorrea/prometheus:2.18
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - icorrea_net

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - icorrea_net
    depends_on:
      - prometheus

networks:
  icorrea_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.39.0.0/16

volumes:
  esdata1:
    driver: local
  graylog_journal:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
